version: '3.8'

services:
  app:
    image: mcr.microsoft.com/devcontainers/go:1-1.24-bookworm
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=crm
      - POSTGRES_USER=crmuser
      - POSTGRES_PASSWORD=crmpassword
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=crm
      - POSTGRES_USER=crmuser
      - POSTGRES_PASSWORD=crmpassword

volumes:
  postgres-data:
